export default {
    NAME: 'USERS',

    // SET
    SET_USERS: 'SET_USERS',
    SET_USER: 'SET_USER',
    SET_AUTH_USER: 'SET_AUTH_USER',
    SET_USERS_BY_ROLE_AND_GROUP: 'SET_USERS_BY_ROLE_AND_GROUP',
    SET_USER_WITH_RATINGS: 'SET_USER_WITH_RATINGS',
    SET_USERS_ATTACHED: 'SET_USERS_ATTACHED',
    SET_USERS_SEARCH_INPUT: 'SET_USERS_SEARCH_INPUT',
    SET_USERS_FILTERS: 'SET_USERS_FILTERS',
    SET_USERS_ONCE_FILTER: 'SET_USERS_ONCE_FILTER',
    SET_USERS_BY_MEETING: 'SET_USERS_BY_MEETING',

    // ACTIONS
    ACTIONS_FETCH_USERS: 'ACTIONS_FETCH_USERS',
    ACTIONS_FETCH_USER: 'ACTIONS_FETCH_USER',
    ACTIONS_FETCH_AUTH_USER: 'ACTIONS_FETCH_AUTH_USER',
    ACTIONS_FETCH_USER_WITH_RATINGS: 'ACTIONS_FETCH_USER_WITH_RATINGS',
    ACTIONS_FETCH_USER_BY_GROUP_AND_ROLE: 'ACTIONS_FETCH_USER_BY_GROUP_AND_ROLE',
    ACTIONS_FETCH_USER_PROFILE: 'ACTIONS_FETCH_USER_PROFILE',
    ACTIONS_FETCH_USERS_CREATE: 'ACTIONS_FETCH_USERS_CREATE',
    ACTIONS_FETCH_USERS_UPDATE: 'ACTIONS_FETCH_USERS_UPDATE',
    ACTIONS_FETCH_USERS_DELETE: 'ACTIONS_FETCH_USERS_DELETE',
    ACTIONS_FETCH_USERS_GET_ATTACHED: 'ACTIONS_FETCH_USERS_GET_ATTACHED',
    ACTIONS_FETCH_USERS_GET_ATTACHED_PARENT: 'ACTIONS_FETCH_USERS_GET_ATTACHED_PARENT',
    ACTIONS_FETCH_USER_SYNC: 'ACTIONS_FETCH_USER_SYNC',
    ACTIONS_FETCH_USERS_BY_MEETING: 'ACTIONS_FETCH_USERS_BY_MEETING',
    ACTIONS_FETCH_UPLOAD_PHOTO: 'ACTIONS_FETCH_UPLOAD_PHOTO',

    // GET
    GET_USERS: 'GET_USERS',
    GET_USERS_SEARCH_INPUT: 'GET_USERS_SEARCH_INPUT',
    GET_USERS_FILTERS: 'GET_USERS_FILTERS',
    GET_USER: 'GET_USER',
    GET_AUTH_USER: 'GET_AUTH_USER',
    GET_USER_WITH_RATINGS: 'GET_USER_WITH_RATINGS',
    GET_USERS_BY_ROLE_AND_GROUP: 'GET_USERS_BY_ROLE_AND_GROUP',
    GET_USERS_ATTACHED: 'GET_USERS_ATTACHED',
    GET_USERS_BY_MEETING: 'GET_USERS_BY_MEETING'
}
