export default {
    NAME: 'CHECKOUT',

    // SET
    SET_CHECKOUT: 'SET_CHECKOUT',
    SET_FORM: 'SET_FORM',
    SET_FORM_FIELD: 'SET_FORM_FIELD',
    SET_COUNT_OF_PRODUCT: 'SET_COUNT_OF_PRODUCT',
    SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',

    // ACTIONS
    ACTIONS_FETCH_CHECKOUT: 'ACTIONS_FETCH_CHECKOUT',

    // GET
    GET_CHECKOUT: 'GET_CHECKOUT',
    GET_FORM: 'GET_FORM'

}
